### ISSUE TITLE
Register package on Packagist

### ISSUE THREAD

**Issue by Anahkiasen** [pocket7878/opauth-flickr#4]
Although this package has a Composer file it's not registered on Packagist. Would be great if it was. :)

**Comment by Anahkiasen** [comment]
Ping ?

**Comment by pocket7878** [comment]
I am sorry for the delay in my response.
Now opauth/flickr available on Packagest and opauth/foursquare too :+1:

**Comment by barryvdh** [comment]
And tag a release perhaps?

**Comment by pocket7878** [comment]
I am so sorry for the delay..
I just create a tag 1.0
