### ISSUE TITLE
Update to use new tmhOAuth

### ISSUE THREAD

**Issue by barryvdh** [pocket7878/opauth-flickr#6]
Is it possible to update to the latest tmhOAuth? And require that via Composer?

I tried just removing it and changing adding `$this->strategy['host']  = 'www.flickr.com/services/oauth/';` to the config, but I get an error:
`oauth_problem=signature_invalid&debug_sbs=POST&http%3A%2F%2Fwww.flickr.com%2Fservices%2Foauth%2Frequest_token&oauth_callback%3`

Any ideas?

**Comment by pocket7878** [comment]
Hmm... Thanks. 
I just created a feature branch to update tmhOAuth to latest version.

**Comment by barryvdh** [comment]
Thanks. But if possible, I would delete the Vendor dir, and just require it in Composer. Or do you need to override some of the functionality?

**Comment by pocket7878** [comment]
I found this problem happend at 0.8.1 and not in 0.8.
I'll try to figure out what is different between these versions.

**Comment by barryvdh** [comment]
The change seems to be that since that release, use_ssl is true by default. Maybe disable that in the config, does that work?

**Comment by barryvdh** [comment]
And some priority changes to config: https://github.com/themattharris/tmhOAuth/commit/02dd58b9ba12ab6b8a0d7781ef6586b2a3c8da43

**Comment by pocket7878** [comment]
Hmm... not working... ;(

**Comment by barryvdh** [comment]
Yes, in defaults it should be token/secret instead of user_token/user_secret.
I'll submit a patch

**Comment by barryvdh** [comment]
oops sorry, that wasn't it.

**Comment by barryvdh** [comment]
Submitted a PR in #7 
Can you verify this works? it does seem to work with Anahkiasen/flickering

**Comment by pocket7878** [comment]
And I just figure out the reason why error happend!!!
I use a (key, secret) to my strategy, and It conflicts with tmhOAuth's secret... 8(

I change these parameter name to api_key, api_secret then work fine!

So I'll fix this problem.. And After that I'll merge your patch!

**Comment by pocket7878** [comment]
I see we found out same solution so I'll just merge you PR :smile:

**Comment by pocket7878** [comment]
create a tag for 1.1.

So I can close this issue now?
